### ISSUE TITLE
[FEATURE-REQUEST]: NixOS compatibility

### ISSUE THREAD

**Issue by N0m4n904** [NoRiskClient/issues#1436]
### Your idea

Please add this to Nix Packages.
I tried to use the AppImage but i wasn't able to because of dependencies.

Adding it to Nix Packages would be really nice.

### Linked issues

https://github.com/NoRiskClient/noriskclient-launcher/issues/106

### Where would this be applied?

Launcher

### What platforms would this affect?

Linux

**Comment by sitolam** [comment]
+1 really want nixos support

**Comment by mzntori** [comment]
this would be amazing

**Comment by mzntori** [comment]
For people that find this in the future that are just interested in using the in-game functionality:

You can get full in-game functionality with this wrapper for prism-launcher by ThatCuteOne (Thanks to them for providing help on the discord :3): https://github.com/ThatCuteOne/nrc-prism-wrapper

**Comment by JuxGD** [comment]
I made a somewhat working derivation, available as a package in [JuxGD/nur-packges](https://github.com/JuxGD/nur-packges/blob/main/pkgs/noriskclient-launcher/default.nix) (I'm not in NUR yet, more on that later) The only problem is that it *can't launch Minecraft at all*, at least not in my system. But I mean the launcher works!

To install it I used flakes (on system config, since I wanted to see if Cachix worked:
- [This is where I'm setting the input](https://github.com/JuxGD/nixconfig/blob/4dba578e7242b12cc7d2d24935db018b476e8210/flake.nix#L33C4-L36C7)
- [This is where I'm declaring the install](https://github.com/JuxGD/nixconfig/blob/4dba578e7242b12cc7d2d24935db018b476e8210/other.nix) (notice the `juxgd` thing near the start and the `juxgd.noriskclient-launcher` in `environment.systemPackages`)

[Cachix is also set up](https://juxgd.cachix.org/), for some reason it's not working in my config but it's there. It does build without it though

It has some errors, I'm not sure how to fix them, I'm trying. If someone more knowledgeable than me could help, I'd greatly appreciate that! These errors are why I haven't added my repo to [NUR](https://github.com/nix-community/NUR) yet

(EDIT: I guess I can mark it as broken and add it to NUR anyways, hold on)

**Comment by mzntori** [comment]
Guess I should have looked here again before opening [this issue](https://github.com/NoRiskClient/issues/issues/2018#issue-3428372152) oops. 

However when I build your derivation I do get the same black screen as described in the issue, honestly it has to be my system at this point. Does my derivation work for you? I don't think we are doing anything significantly different 🤔

**Comment by JuxGD** [comment]
Just built it, your derivation works for me (seemingly just as fine as mine). Hmm. Maybe it's an Nvidia or Wayland thing? I'm on Niri using an RTX 3070 Ti mobile. Though I tried running it inside `labwc`, an X window manager (running it using Xwayland on Niri) and it worked fine there too (edit: just tried on my Plasma 6 X11 session and it also works fine)

Also perhaps we're doing something different in our system/Home Manager configs? Mine are public under my GH as "nixpkgs" and "hmcfg"

**Comment by mzntori** [comment]
After trying on my laptop that also runs nixos but on sway and trying a bunch of other stuff I noticed I used beta drivers on my main machine so i switched to stable and it worked after switching. Then I rebooted and it stopped working again lol. I'll play around with it a bit more and post my findings here :/

**Comment by mzntori** [comment]
Okay so it doesn't work unless I rebuild and switch using a different driver. Lets say my config uses .stable and i switch to .latest and then rebuild it starts working but after a reboot it doesn't

**Comment by JuxGD** [comment]
That's really weird lol, does this happen with other Tauri packages?

Try `$ nix-shell -p fedistar`, that's a Tauri package. If it's not exclusive to NRC then maybe you could report it to nixpkgs

**Comment by mzntori** [comment]
Nope, fedistar works. this is so weird

**Comment by JuxGD** [comment]
????

Idk what else it could be, I'm not a pro NixOS user :p You could try asking around in NixOS' Matrix spaces (or on discourse.nixos.org)

**Comment by mzntori** [comment]
I'll take a look, it feels like some service or something is started on rebuild, but I think I tried all the obvious settings for that already (specifically boot.kernelModules) so I'm just really out of ideas :|

It's funny cause when I upgrade my Nvidia drivers, other stuff like alacritty or zed, which use the gpu start breaking, which is fixed by a simple reboot and I'm not the only one that has that. NRC behaves the exact opposite, which implies that it starts working because it just doesnt use the gpu (which makes sense i guess?) and not because rebuilding does something special.

**Comment by JuxGD** [comment]
Also we should probably talk about this in that other issue lol

**Comment by JuxGD** [comment]
My personal NUR repo has just been added to NUR! `noriskclient-launcher` can now be installed by adding the NUR as an input:

```nix
inputs = {
  nur = {
    url = "github:nix-community/NUR";
    inputs.nixpkgs.follows = "nixpkgs";
  };
};
```

adding the following package override:

```nix
{
  nixpkgs.config.packageOverrides = pkgs: {
    nur = import (builtins.fetchTarball "https://github.com/nix-community/NUR/archive/main.tar.gz") {
      inherit pkgs;
    };
  };
}
```

and listing my package somewhere:

```nix
# for example in system packages
environment.systemPackages = [
  nur.repos.juxgd.noriskclient-launcher
];
```

It still can't launch Minecraft but now it's more easily accessible. Hopefully this will bring it visibility and help bring it to a fully working state!

(edit: also you might have to allow broken packages, since it's marked as broken)
(edit 2: NUR in the input url should be in caps, fixed)

**Comment by mzntori** [comment]
If someone doesn't care about _how_, this flatpak works fully for 0.67.0 on my machine, I think updating doesn't work: https://github.com/Greeenman999/flathubnrc/releases

I think it would still be nice to attempt packaging it with nix :)

**Comment by JuxGD** [comment]
I have some changes to my package I was keeping to myself, they're now present on my nur-packges repo. I renamed the `noriskclient-launcher` package declaration as `noriskclient-launcher-unwrapped`. The ✨NEW✨ `noriskclient-launcher` is an attempt to wrap the other one and give it some runtime dependencies it supposedly uses to launch the game. I got those dependencies from the `prismlauncher` package declaration in nixpkgs

Sadly, I don't know what I'm doing, and the new `noriskclient-launcher` package isn't really showing these dependencies to the launcher at all. I've created an issue on that repository to track this, [here](https://github.com/JuxGD/nur-packges/issues/2).

**Comment by JuxGD** [comment]
Wait lmao check this out https://github.com/NixOS/nixpkgs/issues/348132 people got close like a year ago

**Comment by mzntori** [comment]
Yeah I kinda used some past attempts as reference, but I'm pretty sure they never actually got to the point we are at rn, since it was still in closed beta or something like this. At least that is mentioned in the actual pr

**Comment by copyandexecute** [comment]
closing this issue as I've asked for help on tauri discord + github, we'll track the problem there https://github.com/tauri-apps/tauri/issues/14275 

additionally, flatpak support will be added soon!

**Comment by JuxGD** [comment]
Wait, why's the issue being closed for that reason? The launcher's GUI opens and works, so I don't think it's a Tauri problem, it's just not seeing what it needs to run Minecraft. That issue doesn't really have to do with NixOS compatibility as far as I can see.

Also like, we Nix users always very much appreciate having things available through Nix packaging. It makes reproducing my config easier; part of the point of Nix and NixOS is that one can use them to instantly have a near identical setup as you had before by just using a couple of files. For example if I'm switching computers and I used NixOS I can just move over the configuration files and get nearly the same environment. That's why packaging this for NixOS specifically would be beneficial, it would allow us to have the launcher available instantly when we do the setup, and make pinning specific versions a lot easier as well

**Comment by N0m4n904** [comment]
> Wait, why's the issue being closed for that reason? The launcher's GUI opens and works, so I don't think it's a Tauri problem, it's just not seeing what it needs to run Minecraft. That issue doesn't really have to do with NixOS compatibility as far as I can see.
> 
> Also like, we Nix users always very much appreciate having things available through Nix packaging. It makes reproducing my config easier; part of the point of Nix and NixOS is that one can use them to instantly have a near identical setup as you had before by just using a couple of files. For example if I'm switching computers and I used NixOS I can just move over the configuration files and get nearly the same environment. That's why packaging this for NixOS specifically would be beneficial, it would allow us to have the launcher available instantly when we do the setup, and make pinning specific versions a lot easier as well

Thanks for summarizing it again. I wanted to reopen it myself, but @copyandexecute  already did.

The idea behind this GitHub issue was that the NoRisk client would hopefully be published in the nixpkgs so that it could be easily added to the config and the client could be used.
I hope we will see this in the future, as the client is really promising.

**Comment by H4K0N42** [comment]
We could package this project as a flake and place the `flake.nix` file in the root of the noriskclient-launcher repo. I have installed many projects like this. For example: https://github.com/vicinaehq/vicinae/blob/main/flake.nix

I use flakes often, but I still cant write them. If you could convert the previous packaging attempts for nixpkgs into a flake, we could then install the client with: `nix profile install github:NoRiskClient/noriskclient-launcher`

**Comment by Hythera** [comment]
If someone someone is still interested in this, you could help out with the review of https://github.com/NixOS/nixpkgs/pull/464650 on `nixpkgs` that aimts to add the noriskclient-launcher package. I had to patch out some stuff to get the game launching.

**Comment by Hythera** [comment]
This issue can probably be closed now, as https://github.com/NixOS/nixpkgs/pull/464650 has been merged into master, and will soon be available in `nixpkgs-unstable` and `nixos-unstable`.

**Comment by N0m4n904** [comment]
> This issue can probably be closed now, as [NixOS/nixpkgs#464650](https://github.com/NixOS/nixpkgs/pull/464650) has been merged into master, and will soon be available in `nixpkgs-unstable` and `nixos-unstable`.

Awesome! I will close it, once it's in unstable. Thanks for your work!

**Comment by N0m4n904** [comment]
The `noriskclient-launcher` package is now available in **nixpkgs-unstable**.
Thanks to @Hythera 

Closing this issue now
