### ISSUE TITLE
[CLIENT-FEATURE]: Chat Tabs V3.0 (Check my latest message for checking..)

### ISSUE THREAD

**Issue by BigBrainRobin29** [NoRiskClient/issues#1620]
### Your idea

chat tabs womit man messages zb mit filtern oder so in verschiedenen tabs anzeigen lassen kann

**Comment by copyandexecute** [comment]
atm only for 1.21.10... maybe @S42yt will update for lower version aswell
please check if lower versions break!!!

**Comment by jvcvv** [comment]
<img width="870" height="260" alt="Image" src="https://github.com/user-attachments/assets/bd766a99-14d7-4e52-89a1-58cf20f87445" />
filter pings for every message

**Comment by Schneeander** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/00a4e635-2453-4690-9141-dfeef2edc271" />
I cant move it vertically

**Comment by jvcvv** [comment]
> <img alt="Image" width="1920" height="1080" src="https://private-user-images.githubusercontent.com/193496186/511459542-00a4e635-2453-4690-9141-dfeef2edc271.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI1Mzk1MjYsIm5iZiI6MTc2MjUzOTIyNiwicGF0aCI6Ii8xOTM0OTYxODYvNTExNDU5NTQyLTAwYTRlNjM1LTI0NTMtNDY5MC05MTQxLWRmZWVmMmVkYzI3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwN1QxODEzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzhlOWI0ZDQ5MzY1NTI2ZDY2ZDIwNWM1MWUzNWU0ZjNlZTlmNTA1YWM0MGQ4ODdiMTFlNTJlZDUzMzNhNTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7oCSjYudT5MTD73gZt5F2iX17hMY43qbBJyT-ti6hfc"> I cant move it vertically

works for me

**Comment by jvcvv** [comment]
<img width="561" height="228" alt="Image" src="https://github.com/user-attachments/assets/a7bf6749-4a01-4db6-9ded-790d5fd5af95" />

an option to reset the position and an option to disable chat "moving" would be great

**Comment by Leontix** [comment]
like this 

https://github.com/user-attachments/assets/ce852443-9921-42a0-a58a-f3b034f38957

**Comment by jvcvv** [comment]
<img width="672" height="348" alt="Image" src="https://github.com/user-attachments/assets/2fae0111-2655-46ee-8526-de2413e8c746" />

cant click any options if it overlaps with another chat window

an option to delete all tabs at once would also be nice ^^

**Comment by jvcvv** [comment]
<img width="949" height="811" alt="Image" src="https://github.com/user-attachments/assets/d61a2df9-d90e-4531-bdac-889eeac5e0ed" />

its a bit cut off

**Comment by jvcvv** [comment]
<img width="287" height="123" alt="Image" src="https://github.com/user-attachments/assets/82d567f7-ae74-4b11-a6b6-f2defa5fc120" />

clicking/moving on/the chat triggers filter - chat filter is set to "Jvcv"

**Comment by jvcvv** [comment]
Chat filter doesnt work when mod is turned off

**Comment by jvcvv** [comment]
<img width="672" height="30" alt="Image" src="https://github.com/user-attachments/assets/3c560790-4598-42b2-9db5-581382d1032f" />

seems like the filter still randomly pings sometimes 😹 
Filter set to "Jvcv"

**Comment by copyandexecute** [comment]
- scale nur für bestimmte fenster

**Comment by jvcvv** [comment]
if u go from window screen to fullscreen the chat tab is in the middle and cant be moved to  the side

**Comment by copyandexecute** [comment]
V2

- Fixed Dropdown (Context Menu) Priority
- if u go from window screen to fullscreen the chat tab is in the middle and cant be moved to the side
- Chat filter doesnt work when mod is turned off
- Crashes when sending a message on 1.21.8. It happens because of chat-highlighting
- And i would add a x to delete the chat window but exept that it works all good
- Independent Chat Scale

**Comment by copyandexecute** [comment]
> <img alt="Image" width="287" height="123" src="https://private-user-images.githubusercontent.com/195831243/511465289-82d567f7-ae74-4b11-a6b6-f2defa5fc120.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI2MDM1MTcsIm5iZiI6MTc2MjYwMzIxNywicGF0aCI6Ii8xOTU4MzEyNDMvNTExNDY1Mjg5LTgyZDU2N2Y3LWFlNzQtNGIxMS1hNmI2LWYyZGVmYTVmYzEyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwOFQxMjAwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGRkODczNGUzODdiYzU5MDk1ZGIyODE5Y2U1ZWU2MmFmM2IzMTA1ZTQ5ZmU2NmQ2ZDFhZTI1ZDczM2IyYWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MxqetPRvv4B0CwllDDR-5hRZnGBiEJKSLeVu_nDL-Ck">
> 
> clicking/moving on/the chat triggers filter - chat filter is set to "Jvcv"

cant reproduce?!

**Comment by AAirCrafter** [comment]
habe mal einen neuen tab erstellt und nach oben gemoved, seitdem gibts keinen chat mehr und resetten bringt auch nichts

**Comment by jvcvv** [comment]
- if u go from window screen to fullscreen the chat tab is in the middle and cant be moved to the side
not fixed still happens idk? Even tho i was in fullscreen the whole time

<img width="1350" height="459" alt="Image" src="https://github.com/user-attachments/assets/bb5c793b-4f64-4a21-b3f5-75787ed1a58d" />

**Comment by jvcvv** [comment]
<img width="697" height="96" alt="Image" src="https://github.com/user-attachments/assets/bd655cde-d225-474b-aa5c-6e96a1ee1a13" />
if u enable chat filter on new tab u will only receive the filtered messages? idk if this is intended

**Comment by jvcvv** [comment]
> > <img alt="Image" width="287" height="123" src="https://private-user-images.githubusercontent.com/195831243/511465289-82d567f7-ae74-4b11-a6b6-f2defa5fc120.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI2MDM1MTcsIm5iZiI6MTc2MjYwMzIxNywicGF0aCI6Ii8xOTU4MzEyNDMvNTExNDY1Mjg5LTgyZDU2N2Y3LWFlNzQtNGIxMS1hNmI2LWYyZGVmYTVmYzEyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwOFQxMjAwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGRkODczNGUzODdiYzU5MDk1ZGIyODE5Y2U1ZWU2MmFmM2IzMTA1ZTQ5ZmU2NmQ2ZDFhZTI1ZDczM2IyYWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MxqetPRvv4B0CwllDDR-5hRZnGBiEJKSLeVu_nDL-Ck">
> > clicking/moving on/the chat triggers filter - chat filter is set to "Jvcv"
> 
> cant reproduce?!

Try the following:

1. in main chat enable chat filter for ur ingame name, ignore your messges and highlight the filtered messsage in filter options
2. open a new tab
3. double click? or move the main chat

**Comment by jvcvv** [comment]
<img width="1261" height="1076" alt="Image" src="https://github.com/user-attachments/assets/ea26612a-071b-496a-9a9a-7ced770caa38" />

uhm so somehow double clicking or idk what i did completely removed the chat if mod is turned on 😹 

restart WONT fix it lol

**Comment by copyandexecute** [comment]
> * if u go from window screen to fullscreen the chat tab is in the middle and cant be moved to the side
>       not fixed still happens idk? Even tho i was in fullscreen the whole time
> 
> 
> <img alt="Image" width="1350" height="459" src="https://private-user-images.githubusercontent.com/195831243/511681574-bb5c793b-4f64-4a21-b3f5-75787ed1a58d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI2ODI4NTgsIm5iZiI6MTc2MjY4MjU1OCwicGF0aCI6Ii8xOTU4MzEyNDMvNTExNjgxNTc0LWJiNWM3OTNiLTRmNjQtNGEyMS1iM2Y1LTc1Nzg3ZWQxYTU4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwOVQxMDAyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjEzMDAxMzZhYzU3MWJjZjhlZGM1NjkyMDE5MTIwYmNmMDc3YTYwMDVmMjFjNDNiZGNkMDRlYTc1OWMzMTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qFXRQg9phkaxOnte12ihlLq3l4A8iNdudfcV4Hqj0c4">

?!

**Comment by copyandexecute** [comment]
> > > <img alt="Image" width="287" height="123" src="https://private-user-images.githubusercontent.com/195831243/511465289-82d567f7-ae74-4b11-a6b6-f2defa5fc120.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI2MDM1MTcsIm5iZiI6MTc2MjYwMzIxNywicGF0aCI6Ii8xOTU4MzEyNDMvNTExNDY1Mjg5LTgyZDU2N2Y3LWFlNzQtNGIxMS1hNmI2LWYyZGVmYTVmYzEyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwOFQxMjAwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGRkODczNGUzODdiYzU5MDk1ZGIyODE5Y2U1ZWU2MmFmM2IzMTA1ZTQ5ZmU2NmQ2ZDFhZTI1ZDczM2IyYWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MxqetPRvv4B0CwllDDR-5hRZnGBiEJKSLeVu_nDL-Ck">
> > > clicking/moving on/the chat triggers filter - chat filter is set to "Jvcv"
> > 
> > 
> > cant reproduce?!
> 
> Try the following:
> 
>     1. in main chat enable chat filter for ur ingame name, ignore your messges and highlight the filtered messsage in filter options
> 
>     2. open a new tab
> 
>     3. double click? or move the main chat

thanks alot, will fix

**Comment by copyandexecute** [comment]
### Things I hopefully fixed in V3

- clicking/moving on/the chat triggers filter - chat filter is set to "Jvcv" 
- resetting brings chat back to normal position
- habe mal einen neuen tab erstellt und nach oben gemoved, seitdem gibts keinen chat mehr und resetten bringt auch nichts

**Comment by copyandexecute** [comment]
> <img alt="Image" width="697" height="96" src="https://private-user-images.githubusercontent.com/195831243/511681780-bd655cde-d225-474b-aa5c-6e96a1ee1a13.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI2ODgwODQsIm5iZiI6MTc2MjY4Nzc4NCwicGF0aCI6Ii8xOTU4MzEyNDMvNTExNjgxNzgwLWJkNjU1Y2RlLWQyMjUtNDc0Yi1hYTVjLTZlOTZhMWVlMWExMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwOVQxMTI5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDg1NzkyZDAxODY5NTc4MTE3Y2RkMzc2Y2ViNjMwYWEyZWMyNjRiNWI0YTkxNzkyZjgxOGIxNjZhYzA2NGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Un5k-oBIStUAGms8ODyhxKQUmWfVtRUnRT0D-ULdFuM"> if u enable chat filter on new tab u will only receive the filtered messages? idk if this is intended

yup thats kinda "intended" I'm waiting for the feedback of users who actively use this feature

**Comment by copyandexecute** [comment]
> habe mal einen neuen tab erstellt und nach oben gemoved, seitdem gibts keinen chat mehr und resetten bringt auch nichts

thanks will fix!

**Comment by jvcvv** [comment]
<img width="275" height="49" alt="Image" src="https://github.com/user-attachments/assets/d8c88b58-33b0-4208-8937-813c9b4fc37f" />

<img width="258" height="63" alt="Image" src="https://github.com/user-attachments/assets/f6b795f1-f3b2-4524-be16-8f7826a17cef" />
1 message in new tab = 5 notifications in main chat

this happens randomly??? Or fixed idk?

**Comment by jvcvv** [comment]
<img width="29" height="252" alt="Image" src="https://github.com/user-attachments/assets/8ee6f926-b73e-47ef-851a-d892deab8bb7" />

<img width="27" height="240" alt="Image" src="https://github.com/user-attachments/assets/02fff8b8-6483-49e7-843f-b9b7e4352a1b" />

so with the mod on, the whole chat is like 2-3 pixel moved to the right, idk if u see the difference on picture but yea, other than those 2 things it seems to work now !

**Comment by S42yt** [comment]
> atm only for 1.21.10... maybe [@S42yt](https://github.com/S42yt) will update for lower version aswell please check if lower versions break!!!

yeah i can do it

**Comment by S42yt** [comment]
multiversion wont be that hard after the core feature is already implemented ig

**Comment by jvcvv** [comment]
resetting the mod also resets the filter? Thought it should only reset position
